apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: doormen.auth.example.com
spec:
  group: auth.example.com
  names:
    kind: Doorman
    listKind: DoormanList
    plural: doormen
    singular: doorman
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Doorman is the Schema for the doormen API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: DoormanSpec defines the desired state of Doorman
          properties:
            database:
              description: Define database config Database size should only be provided
                for operator managed database
              properties:
                hostname:
                  type: string
                name:
                  type: string
                password:
                  type: string
                size:
                  format: int32
                  type: integer
                username:
                  type: string
              type: object
            replicas:
              description: Define number of instances to be deployed
              format: int32
              type: integer
          type: object
        status:
          description: DoormanStatus defines the observed state of Doorman
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
