apiVersion: apps/v1
kind: Deployment
metadata:
  name: doorman-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: doorman-operator
  template:
    metadata:
      labels:
        name: doorman-operator
    spec:
      serviceAccountName: doorman-operator
      containers:
        - name: doorman-operator
          # Replace this with the built image name
          image: quay.io/eochieng/doorman-operator:v0.0.1
          command:
          - doorman-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "doorman-operator"
